name: Publish NuGet

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Test
        run: dotnet test Keycloak.sln -c Release

      - name: Pack
        run: dotnet pack Keycloak/Keycloak.csproj -c Release -o ./artifacts

      - name: NuGet login (OIDC)
        uses: NuGet/login@v1
        id: login
        with:
          user: MattUssher

      - name: Push to NuGet.org
        run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --skip-duplicate

      - name: Push symbols
        run: dotnet nuget push ./artifacts/*.snupkg --source https://api.nuget.org/v3/index.json --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --skip-duplicate
